<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="9" passed="0" failed="0" skipped="9">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-12-23T23:14:19 IST" name="Default suite" finished-at="2021-12-23T23:14:19 IST" duration-ms="139">
    <groups>
    </groups>
    <test started-at="2021-12-23T23:14:19 IST" name="Default test" finished-at="2021-12-23T23:14:19 IST" duration-ms="139">
      <class name="com.cs.arris.Tests.TC01_Simple_Test">
        <test-method is-config="true" signature="beforeSuite(java.lang.String,java.lang.String)[pri:0, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:19 IST" name="beforeSuite" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1640281459298" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Parameter 'platform' is required by BeforeSuite on method beforeSuite but has not been marked @Optional or defined
in /private/var/folders/0n/gztfs3315sqflgmf8691xcwr0000gp/T/testng-eclipse--1072445143/testng-customsuite.xml]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Parameter 'platform' is required by BeforeSuite on method beforeSuite but has not been marked @Optional or defined
in /private/var/folders/0n/gztfs3315sqflgmf8691xcwr0000gp/T/testng-eclipse--1072445143/testng-customsuite.xml
at org.testng.internal.Parameters.createParams(Parameters.java:270)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:358)
at org.testng.internal.Parameters.createParameters(Parameters.java:700)
at org.testng.internal.Parameters.createConfigurationParameters(Parameters.java:168)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:19 IST" name="beforeTest" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1640281459322" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:19 IST" name="beforeClass" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1640281459358" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:19 IST" name="beforeMethod" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1640281459371" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:19 IST" name="beforeMethod" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1640281459372" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="Login_And_Onboard()[pri:1, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:19 IST" name="Login_And_Onboard" finished-at="2021-12-23T23:14:19 IST" duration-ms="0" status="SKIP">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Parameter 'platform' is required by BeforeSuite on method beforeSuite but has not been marked @Optional or defined
in /private/var/folders/0n/gztfs3315sqflgmf8691xcwr0000gp/T/testng-eclipse--1072445143/testng-customsuite.xml]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Parameter 'platform' is required by BeforeSuite on method beforeSuite but has not been marked @Optional or defined
in /private/var/folders/0n/gztfs3315sqflgmf8691xcwr0000gp/T/testng-eclipse--1072445143/testng-customsuite.xml
at org.testng.internal.Parameters.createParams(Parameters.java:270)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:358)
at org.testng.internal.Parameters.createParameters(Parameters.java:700)
at org.testng.internal.Parameters.createConfigurationParameters(Parameters.java:168)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_And_Onboard -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:19 IST" name="afterMethod" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1640281459384" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="Verify_Home_UI_Page()[pri:2, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:19 IST" name="Verify_Home_UI_Page" finished-at="2021-12-23T23:14:19 IST" depends-on-methods="com.cs.arris.Tests.TC01_Simple_Test.Login_And_Onboard" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Simple_Test.Verify_Home_UI_Page()[pri:2, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Simple_Test.Verify_Home_UI_Page()[pri:2, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Home_UI_Page -->
        <test-method signature="Verify_Home_Device_Signal_Strength_Navigation()[pri:3, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:19 IST" name="Verify_Home_Device_Signal_Strength_Navigation" finished-at="2021-12-23T23:14:19 IST" depends-on-methods="com.cs.arris.Tests.TC01_Simple_Test.Login_And_Onboard, com.cs.arris.Tests.TC01_Simple_Test.Verify_Home_UI_Page" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Simple_Test.Verify_Home_Device_Signal_Strength_Navigation()[pri:3, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Simple_Test.Verify_Home_Device_Signal_Strength_Navigation()[pri:3, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Home_Device_Signal_Strength_Navigation -->
        <test-method signature="Verify_Home_Speed_Test_History_Navigation()[pri:4, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:19 IST" name="Verify_Home_Speed_Test_History_Navigation" finished-at="2021-12-23T23:14:19 IST" depends-on-methods="com.cs.arris.Tests.TC01_Simple_Test.Login_And_Onboard" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Simple_Test.Verify_Home_Speed_Test_History_Navigation()[pri:4, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Simple_Test.Verify_Home_Speed_Test_History_Navigation()[pri:4, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Home_Speed_Test_History_Navigation -->
        <test-method signature="Verify_Home_Currently_Blocked_Devices_Navigation()[pri:5, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:19 IST" name="Verify_Home_Currently_Blocked_Devices_Navigation" finished-at="2021-12-23T23:14:19 IST" depends-on-methods="com.cs.arris.Tests.TC01_Simple_Test.Login_And_Onboard" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Simple_Test.Verify_Home_Currently_Blocked_Devices_Navigation()[pri:5, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Simple_Test.Verify_Home_Currently_Blocked_Devices_Navigation()[pri:5, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Home_Currently_Blocked_Devices_Navigation -->
        <test-method signature="Verify_Home_Main_Devices_Navigation()[pri:6, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:19 IST" name="Verify_Home_Main_Devices_Navigation" finished-at="2021-12-23T23:14:19 IST" depends-on-methods="com.cs.arris.Tests.TC01_Simple_Test.Login_And_Onboard" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Simple_Test.Verify_Home_Main_Devices_Navigation()[pri:6, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Simple_Test.Verify_Home_Main_Devices_Navigation()[pri:6, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Home_Main_Devices_Navigation -->
        <test-method signature="Verify_Home_Total_Devices_Navigation()[pri:7, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:19 IST" name="Verify_Home_Total_Devices_Navigation" finished-at="2021-12-23T23:14:19 IST" depends-on-methods="com.cs.arris.Tests.TC01_Simple_Test.Login_And_Onboard" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Simple_Test.Verify_Home_Total_Devices_Navigation()[pri:7, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Simple_Test.Verify_Home_Total_Devices_Navigation()[pri:7, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Home_Total_Devices_Navigation -->
        <test-method signature="Verify_Home_Hamburger_Navigation()[pri:8, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:19 IST" name="Verify_Home_Hamburger_Navigation" finished-at="2021-12-23T23:14:19 IST" depends-on-methods="com.cs.arris.Tests.TC01_Simple_Test.Login_And_Onboard" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Simple_Test.Verify_Home_Hamburger_Navigation()[pri:8, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Simple_Test.Verify_Home_Hamburger_Navigation()[pri:8, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Home_Hamburger_Navigation -->
        <test-method signature="Verify_Home_Notifications_Navigation()[pri:9, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:19 IST" name="Verify_Home_Notifications_Navigation" finished-at="2021-12-23T23:14:19 IST" depends-on-methods="com.cs.arris.Tests.TC01_Simple_Test.Login_And_Onboard" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Simple_Test.Verify_Home_Notifications_Navigation()[pri:9, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Simple_Test.Verify_Home_Notifications_Navigation()[pri:9, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Home_Notifications_Navigation -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:19 IST" name="afterTest" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1640281459458" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:com.cs.arris.Tests.TC01_Simple_Test@9cb8225]" started-at="2021-12-23T23:14:24 IST" name="afterSuite" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1640281464614" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.cs.arris.Tests.TC01_Simple_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
